######################################################################
# Automatically generated by qmake (2.01a) Sun May 30 00:57:00 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qt_hello_world.cpp

#enable openGL
QT += opengl
